sql_source_url: 'mysql://root:admin@127.0.0.1:3306/ecommerce_sample'
data_warehouse_url: 'mysql://root:admin@localhost:3306/e_commerce_dw'
mappings:
  customer:
    customer_id: id
    customer_email: email
    customer_last_name: last_name
    customer_first_name: first_name
  product:
    product_id: id
    product_sku: sku
    product_category: category
    product_name: name
    product_price: price
  order:
    order_id: id
    order_status: status
    order_date: created_at
  order_item:
    order_item_id: id
    order_item_quantity: quantity
    order_item_unit_price: unit_price
segment_map:
  Champions: [ '555', '554', '544', '545', '454', '455', '445' ]
  Loyal Customers: [
    '543', '444', '435', '355', '354', '345', '344',
    '335', '553', '533', '453', '353'
  ]
  New Customers: [ '512', '511', '422', '421', '412', '411', '311' ]
  Promising: [
    '551', '552', '541', '542', '525', '524', '523', '522',
    '521', '515', '514', '513', '532', '531', '425', '424',
    '413', '414', '415', '315', '314', '313', '452', '451',
    '442', '441', '431', '433', '432', '423', '352', '351',
    '342', '341', '333', '323', '535', '534', '443', '434',
    '343', '334', '325', '324'
  ]
  At Risk: [
    '255', '254', '245', '244', '253', '252', '243', '242',
    '235', '234', '225', '224', '331', '321', '312', '221',
    '213', '231', '241', '251', '332', '322', '233', '232',
    '223', '222', '212', '211', '155', '154', '144', '214',
    '215', '115'
  ]
  Lost Customers: [
    '111', '112', '121', '131', '141', '151', '153',
    '152', '145', '143', '142', '135', '134', '133',
    '125', '124', '132', '123', '122', '114', '113'
  ]
