dim_customer:
  customer_id: id
  customer_email: email
  customer_last_name: last_name
  customer_first_name: first_name
  customer_registration_date: registration_date
dim_product:
  id:
  sku:
  category:
  name:
fact_order:
  order_id: id
  customer_id:
  order_status: status
  order_date: created_at
fact_order_item:
  order_item_id: id
  order_id:
  order_item_product_sku: product_sku
  order_item_quantity: quantity
  order_item_unit_price: unit_price
